[package]
name = "horologe-in-memory"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
horologe.workspace = true
tokio.workspace = true
uuid = { workspace = true, features = ["v4"] }
